// Form name → reference prefix mapping
// Used by the server to generate reference numbers for form submissions
module.exports = {
  'Apply for a Permit to Move a Building, House or Boat on Public Roads': 'VEP',
  'Claim for Unemployment Benefit': 'UB',
  'National Insurance Contributions Certificate (D.P. 10)': 'DP10',
  'Register for the NIS Online Social Security Service': 'NREG',
  'Register as an Employer for NIS Online Services': 'EREG',
  'Direct Deposit Form': 'DD',
  'Pensioner Declaration Form': 'PD',
  'Self-Employment Registration': 'SER',
  'Self-employed Contributions Certificate': 'SEC',
  'Termination of Services / Layoff Certificate': 'TOC',
  'NIS Life Certificate': 'LC',
  'NIS Educational Status Form': 'ESF',
  'Claim for Old Age Contributory Pension': 'OAP',
  // CAIPO forms
  'Articles of Reincorporation': 'ARI',
  'Declaration of Compliance (Companies Act Cap. 308)': 'DEC',
  'Declaration of Compliance (Non-Profit Company)': 'DNP',
  'Registration of Business Name': 'BNR',
  'Form of Application for Registration of a Business Name (Form I)': 'BNR',
  'Registered Agent Authorisation': 'RAG',
  'URL / Domain Name Declaration': 'URL',
  'CARICOM Point of Entry / Departure / Inland Complaints Form': 'CCF',
  'Financial Statements Exemption (Companies Act Cap. 308)': 'FSE',
  'Company Name Search and Reservation (Form 33)': 'CNS',
  'Geographical Indications Agent Authorisation (Cap. 320)': 'GAA',
  'International Business Company Licence Application (Cap. 77)': 'IBC',
  'Form 1 — Application for a Licence as an International Business Company': 'IBC',
  'Society with Restricted Liability Name Search (Form 15)': 'SRL',
  'Request for Name Search and Name Reservation': 'SRL',
  'Declaration of URL / Domain Name Ownership for Company Incorporation': 'URL',
  'Geographical Indications Agent Authorisation': 'GAA',
  'Form of Authorisation of Agent in a Matter or Proceeding Under the Act': 'GAA',
  'Registered Agent Application': 'RAG',
  'Apply to Become a Registered Agent with CAIPO': 'RAG',
  // NAB forms
  'Seniors\' Recreational Activities Programme': 'SRAP',
  'Application for Home Care Services': 'HCP',
  'Community Elder Care Programme': 'CEC',
  // NHC / Ministry of Housing forms
  'Application to Use State Land': 'SLU',
  // Immigration forms
  'CARICOM Indefinite Stay Application': 'CIS',
  'Certificate by Non-Immigrant Student (Form H-2)': 'CSH',
  'Certificate of Eligibility for Non-Immigrant Student Status (H-1)': 'SEL',
  'Citizenship Affidavit': 'CAF',
  'Commonwealth Citizenship Registration': 'CCR',
  'Immigrant Status and Non-National Registration': 'IMM',
  'Permanent Resident Registration': 'PRR',
  'Registration as a Citizen of Barbados (Adult)': 'CRA',
  'Registration as a Citizen of Barbados by virtue of Marriage': 'CRM',
  'Registration as a Citizen of Barbados (Under 18)': 'CRU',
  'Request for Certificate of Citizenship by Descent': 'CCD',
  'Application for Short Term Work Permit or Training Attachment': 'SWP',
  'Application for Work Permit / Extension / Job Offer for Non-Immigrant Employment': 'WPE',
  // NHC forms
  'Application for Rental Unit/Lot': 'NHC',
};
